; Milo832 GPU Shader
; Generated by milo_glsl compiler

; in v_texcoord -> r2
; out fragColor -> r4

; Function: main
main:
    mov r12, r2  ; .x
    mov r8, r12
    mov r13, r3  ; .y
    mov r9, r13
    addi r14, r0, 0x3F000000  ; 0.500000
    mov r10, r14
    addi r15, r0, 0x3F800000  ; 1.000000
    mov r11, r15
    mov r4, r8
    mov r5, r9
    mov r6, r10
    mov r7, r11
    exit

