; Milo832 GPU Shader
; Generated by milo_glsl compiler

; in v_texcoord -> r2
; out fragColor -> r4

; Function: main
main:
    mov r9, r2  ; .x
    addi r10, r0, 0x40000000  ; 2.000000
    fmul r11, r9, r10
    mov r8, r11  ; a
    mov r13, r3  ; .y
    addi r14, r0, 0x3F000000  ; 0.500000
    fadd r15, r13, r14
    mov r12, r15  ; b
    fmul r17, r8, r12
    mov r16, r17  ; c
    addi r19, r0, 0x3DCCCCCD  ; 0.100000
    fadd r20, r16, r19
    sqrt r21, r20
    mov r18, r21  ; d
    mov r22, r8
    mov r23, r12
    mov r24, r16
    mov r25, r18
    mov r4, r22
    mov r5, r23
    mov r6, r24
    mov r7, r25
    exit

