; Milo832 GPU Shader
; Generated by milo_glsl compiler

; in v_texcoord -> r2
; out fragColor -> r4

; Function: main
main:
    mov r9, r2  ; .x
    addi r10, r0, 0x40C90E56  ; 6.283000
    fmul r11, r9, r10
    sin r12, r11
    mov r8, r12  ; s
    mov r14, r3  ; .y
    addi r15, r0, 0x40C90E56  ; 6.283000
    fmul r16, r14, r15
    cos r17, r16
    mov r13, r17  ; c
    mov r19, r2  ; .x
    mov r20, r2  ; .x
    fmul r21, r19, r20
    mov r22, r3  ; .y
    mov r23, r3  ; .y
    fmul r24, r22, r23
    fadd r25, r21, r24
    sqrt r26, r25
    mov r18, r26  ; e
    addi r31, r0, 0x3F000000  ; 0.500000
    fmul r32, r8, r31
    addi r33, r0, 0x3F000000  ; 0.500000
    fadd r34, r32, r33
    mov r27, r34
    addi r35, r0, 0x3F000000  ; 0.500000
    fmul r36, r13, r35
    addi r37, r0, 0x3F000000  ; 0.500000
    fadd r38, r36, r37
    mov r28, r38
    mov r29, r18
    addi r39, r0, 0x3F800000  ; 1.000000
    mov r30, r39
    mov r4, r27
    mov r5, r28
    mov r6, r29
    mov r7, r30
    exit

